export const MOUSE_FIELD_ORDER = [
  'id',
  'brand',
  'model',
  'base_model',
  'category',
  'cardTags',
  'featured',
  'release_date',
  'discontinued',
  'sku',
  'price_range',
  'colors',
  'design',
  'lighting',
  'rgb',
  'connection',
  'connectivity',
  'computer_side_connector',
  'mouse_side_connector',
  'bluetooth',
  'cable_type',
  'paracord',
  'wireless_charging',
  'battery_hours',
  'adjustable_weight',
  'feet_material',
  'coating',
  'honeycomb_frame',
  'silent_clicks',
  'weight',
  'material',
  'lngth',
  'width',
  'height',
  'form_factor',
  'shape',
  'hump',
  'front_flare',
  'thumb_rest',
  'grip',
  'hand_size',
  'mcu',
  'mcu_link',
  'sensor',
  'sensor_brand',
  'sensor_date',
  'sensor_link',
  'sensor_type',
  'flawless_sensor',
  'sensor_latency',
  'sensor_latency_list',
  'shift_latency',
  'polling_rate',
  'dpi',
  'ips',
  'acceleration',
  'lift',
  'lift_settings',
  'motion_sync',
  'hardware_acceleration',
  'smoothing',
  'nvidia_reflex',
  'switch',
  'switch_brand',
  'switch_type',
  'switches_link',
  'hot_swappable',
  'debounce',
  'click_latency',
  'click_latency_list',
  'click_force',
  'encoder',
  'encoder_brand',
  'encoder_link',
  'side_buttons',
  'middle_buttons',
  'programmable_buttons',
  'tilt_scroll_wheel',
  'adjustable_scroll_wheel',
  'onboard_memory',
  'onboard_memory_value',
  'profile_switching'
];

export const ANCHOR_FIELDS = [
  'weight',
  'material',
  'lngth',
  'width',
  'height',
  'form_factor',
  'shape',
  'hump',
  'front_flare',
  'thumb_rest',
  'sensor',
  'sensor_brand',
  'polling_rate',
  'dpi',
  'ips',
  'acceleration',
  'switch',
  'switch_brand',
  'hot_swappable',
  'side_buttons',
  'middle_buttons'
];

export const INSTRUMENTED_FIELDS = new Set([
  'sensor_latency',
  'sensor_latency_list',
  'shift_latency',
  'click_latency',
  'click_latency_list',
  'click_force'
]);

export const COMMONLY_WRONG_FIELDS = new Set([
  'weight',
  'lngth',
  'width',
  'height',
  'sensor',
  'polling_rate',
  'dpi',
  'ips',
  'acceleration',
  'switch',
  'side_buttons',
  'middle_buttons'
]);

export const DEFAULT_REQUIRED_FIELDS = [
  'identity.brand',
  'identity.model',
  'fields.weight',
  'fields.sensor',
  'fields.polling_rate',
  'fields.dpi',
  'fields.connection',
  'fields.side_buttons'
];

export const BOOLEAN_FIELDS = new Set([
  'featured',
  'discontinued',
  'rgb',
  'bluetooth',
  'paracord',
  'wireless_charging',
  'adjustable_weight',
  'honeycomb_frame',
  'silent_clicks',
  'flawless_sensor',
  'motion_sync',
  'hardware_acceleration',
  'smoothing',
  'nvidia_reflex',
  'hot_swappable',
  'tilt_scroll_wheel',
  'adjustable_scroll_wheel',
  'onboard_memory',
  'profile_switching'
]);

export const NUMERIC_FIELDS = new Set([
  'battery_hours',
  'weight',
  'lngth',
  'width',
  'height',
  'sensor_latency',
  'shift_latency',
  'dpi',
  'ips',
  'acceleration',
  'lift',
  'debounce',
  'click_latency',
  'click_force',
  'side_buttons',
  'middle_buttons',
  'programmable_buttons',
  'onboard_memory_value'
]);

export const LIST_FIELDS = new Set([
  'cardTags',
  'colors',
  'connectivity',
  'grip',
  'hand_size',
  'lift_settings',
  'sensor_latency_list',
  'polling_rate',
  'click_latency_list'
]);

export const KNOWN_LIST_VALUES = {
  form_factor: ['symmetrical', 'ergonomic', 'ambi'],
  shape: ['low', 'mid', 'high'],
  connection: ['wired', 'wireless', 'dual'],
  feet_material: ['ptfe', 'glass', 'uhmwpe'],
  sensor_brand: ['pixart', 'razer', 'logitech', 'steelseries']
};

export const INSTRUMENTED_HOST_HINTS = new Set(['rtings.com', 'techpowerup.com']);
